export enum Icon {
	Call = 'fas fa-mobile-alt',
	Close = 'fas fa-times',
	Text = 'fas fa-comment-dots',
	Gift = 'fas fa-gift',
	Edit = 'fas fa-edit',
	Delete = 'fas fa-trash-alt',
	Down = 'fas fa-chevron-down',
	Nav = 'fas fa-arrow-right fa-rotate-335',
	Search = 'fas fa-search',
	Solar = 'fas fa-sun',
	Lunar = 'fas fa-moon',
	Recipient = 'fas fa-recipient-cake',
	View = 'fas fa-eye',
}